import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import  Providers from '../components/Provider'
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "CyberMart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar/>
          {children}
        </Providers>

        <Toaster position="top-center"></Toaster>
      </body>
    </html>
  );
}
